WebCourseProject_Vasilyev/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebCourseProject_Vasilyev.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebCourseProject_Vasilyev/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebCourseProject_Vasilyev.LogicServices;
using WebCourseProject_Vasilyev.Model;
using WebCourseProject_Vasilyev.Model.Entity;

namespace WebCourseProject_Vasilyev.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ItemsLogicService itemsLogicService;
        private List<Item> items;
        public IndexModel(ILogger<IndexModel> logger, ItemsLogicService itemsLogicService)
        {
            _logger = logger;
            this.itemsLogicService = itemsLogicService;
        }
        public async Task<IActionResult> OnPostAsync(string searchTerm)
        {
            // Получаем список товаров из базы данных
            this.items = await itemsLogicService.GetItemsAsync();

            // Фильтруем список товаров, чтобы показывать только те, 
            // у которых в имени содержится строка поиска
            if (!string.IsNullOrEmpty(searchTerm))
            {
                items = items.Where(i => i.Name.ToLower().Contains(searchTerm.ToLower())).ToList();
            }

            // Возвращаем список товаров на страницу Index
            return Page();
        }

        public async Task OnGet()
        {
            this.items = await itemsLogicService.GetItemsAsync();
        }
        public async Task<List<Item>> GetItemsAsync()
        {
            this.items = await itemsLogicService.GetItemsAsync();
            return items;
        }

        public async Task OnPostAddToCart(int itemId)
        {
            // Обработка запроса
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                using (var context = new DBContext())
                { 
                    var shoppingCart = await context.ShoppingCarts
                        .Include(n=>n.Buyer)
                        .Include(n=>n.CartItems)
                        .FirstOrDefaultAsync(n=>n.Buyer.UserID == userId);
                    if (shoppingCart == null)
                    {
                        var newShoppingCart = new ShoppingCart();
                        newShoppingCart.CartItems = null;
                        newShoppingCart.ShippingAddress = "";
                        newShoppingCart.PaymentMethod = "";
                        newShoppingCart.Buyer = await context.Buyers
                            .FirstOrDefaultAsync(n => n.UserID == userId);
                        //shoppingCart.Buyer = await _context.Buyers.FirstOrDefaultAsync(n => n.Id == id);
                        await context.ShoppingCarts.AddAsync(shoppingCart);
                        await context.SaveChangesAsync();

                    }
                    foreach (var item in shoppingCart.CartItems) {
                        Console.WriteLine(item.Id + ";q:" + item.Quantity);
                    }
                    var component = await context.ShoppingCartComponents
                        .Include(n => n.item)
                        .FirstOrDefaultAsync(n => n.item.Id == itemId);

                    if (component != null)
                    {
                        component.Quantity += 1;
                        await context.SaveChangesAsync();
                        return;
                    }
                    else
                    {
                        var newComp = new ShoppingCartComponent();
                        newComp.Quantity = 1;
                        newComp.item = await context.Items.FirstOrDefaultAsync(item => item.Id == itemId);
                        shoppingCart.CartItems.Add(newComp);
                        await context.ShoppingCartComponents.AddAsync(newComp);
                        await context.SaveChangesAsync();
                        return;
                    }

                }
            }
            catch(Exception ex) {
                Console.WriteLine(ex.Message);
            }
        }

    }
}

WebCourseProject_Vasilyev/Pages/ItemPage.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebCourseProject_Vasilyev.Areas.Identity.Data;
using WebCourseProject_Vasilyev.LogicServices;
using WebCourseProject_Vasilyev.Model;
using WebCourseProject_Vasilyev.Model.Entity;

namespace WebCourseProject_Vasilyev.Pages
{
    public class ItemPageModel : PageModel
    {
		private readonly ILogger<IndexModel> _logger;
		private ItemsLogicService itemsLogicService;
        public Item item { get; set; }
        public ItemPageModel(ILogger<IndexModel> logger, ItemsLogicService itemsLogicService)
        {
			_logger = logger;
			this.itemsLogicService = itemsLogicService;
		}
		public async Task<IActionResult> OnGet(int id)
        {
            this.item = await itemsLogicService.GetItemAsync(id);
            return Page();
        }
    }
}

WebCourseProject_Vasilyev/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebCourseProject_Vasilyev.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebCourseProject_Vasilyev/Pages/SellerPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCourseProject_Vasilyev.LogicServices;
using WebCourseProject_Vasilyev.Model.Entity;

namespace WebCourseProject_Vasilyev.Pages
{
    public class SellerPageModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private ItemsLogicService itemsLogicService;
        private List<Item> items;
        public Seller seller;
        public SellerPageModel(ILogger<IndexModel> logger, ItemsLogicService itemsLogicService)
        {
            _logger = logger;
            this.itemsLogicService = itemsLogicService;
        }
        public async Task<IActionResult> OnGet(int id)
        {
            this.items = await itemsLogicService.GetItemsBySellerAsync(id); 
            //TODO
            seller = items[0].Seller;
            return Page();
        }
        public async Task<List<Item>> GetItemsAsync()
        {
            return items;
        }
    }
}

WebCourseProject_Vasilyev/Pages/ShoppingCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebCourseProject_Vasilyev.Model.Entity;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using WebCourseProject_Vasilyev.Areas.Identity.Data;

namespace WebCourseProject_Vasilyev.Pages
{
    public class ShoppingCartModel : PageModel
    {
        public ShoppingCart shoppingCart { get; set; }
        private readonly WebCourseProject_Vasilyev.Model.DBContext _context;
        public ShoppingCartModel(WebCourseProject_Vasilyev.Model.DBContext context)
        {
            _context = context;
        }
        public string TotalCostsText;
        private bool showMessage;
        public async Task OnGet()
        {
            if (showMessage)
            {
                TempData["SuccessMessage"] = "Успешно куплено.";
            }
            else
            {
                TempData.Remove("SuccessMessage");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            shoppingCart = await _context.ShoppingCarts
                .Include(n => n.CartItems)
                    .ThenInclude(ci => ci.item)
                .Include(n => n.Buyer)
                .FirstOrDefaultAsync(n => n.Buyer.UserID == userId);
            if(shoppingCart== null)
            {
                var shoppingCart = new ShoppingCart();
                shoppingCart.CartItems = null;
                shoppingCart.ShippingAddress = "";
                shoppingCart.PaymentMethod = "";
                shoppingCart.Buyer = await _context.Buyers
                .FirstOrDefaultAsync(n => n.UserID == userId);
                //shoppingCart.Buyer = await _context.Buyers.FirstOrDefaultAsync(n => n.Id == id);
                await _context.ShoppingCarts.AddAsync(shoppingCart);
                await _context.SaveChangesAsync();

            }
            double total_cost = 0;
            foreach(var component in shoppingCart.CartItems)
            {
                total_cost += (double)component.item.Price * component.Quantity;
            }
            TotalCostsText = "Общая стоимость: " + total_cost + "₽";
        }
        public IActionResult OnPostBuyButtonClick()
        {
            _context.ShoppingCarts.Remove(_context.ShoppingCarts
                .Include(n => n.CartItems)
                    .ThenInclude(ci => ci.item)
                .Include(n => n.Buyer)
                .FirstOrDefault(n => n.Buyer.UserID == User.FindFirstValue(ClaimTypes.NameIdentifier)));
            _context.SaveChanges();
            showMessage = true;
            return Page();
        }
    }
}

WebCourseProject_Vasilyev/Pages/Index.cshtml
@page
@using WebCourseProject_Vasilyev.LogicServices;
@model IndexModel
@using Microsoft.AspNetCore.Authorization;
@attribute [Authorize]
@{
    ViewData["Title"] = "Home page";
}
<link rel="stylesheet" href="~/css/Items.css" />
<style>
    .product-seller a {
        color: green;
        text-decoration: none;
        font-weight: bolder;
    }

</style>
<div class="text-center">
    @foreach (var item in await @Model.GetItemsAsync())
    {
        <div class="product">
            <a asp-page="/ItemPage" asp-route-id="@item.Id">
                <div class="product-image">
                    @if(String.IsNullOrEmpty(item.PhotoPath)){
                        <img src="~/ItemImages/no_photo.webp">
                    }
                    else
                    {
                        <img src="@item.PhotoPath">
                    }
                </div>
            </a>
            <div class="product-name">@item.Name</div>
            @if (item.InStock)
            {
                <div style="color: green">
                    В наличии
                </div>
                <div class="product-price">@item.Price ₽</div>
                <div class="product-seller">Продавец: <a asp-page="/SellerPage" asp-route-id="@item.Seller.Id">@item.Seller.Name</a></div>
                <form method="post" asp-page-handler="AddToCart" asp-asp-page-handler="AddToCart">
                    <input type="hidden" name="itemId" value="@item.Id">
                    <button type="submit" class="btn btn-success">В корзину</button>
                </form>
                
            }
            else
            {
                    <div style="color: darkred">
                        Нет в наличии
                    </div>
                    <div class="product-price">@item.Price ₽</div>
                    <div class="product-seller">Продавец: <a asp-page="/SellerPage" asp-route-id="@item.Seller.Id">@item.Seller.Name</a></div>
                    <button class="btn btn-danger">Уведомить о поступлении</button>
            }
            
        </div>

    }
</div>

WebCourseProject_Vasilyev/Pages/ItemPage.cshtml
@page
@model WebCourseProject_Vasilyev.Pages.ItemPageModel
@{
	ViewData["Title"] = "Home page";
}
@using Microsoft.AspNetCore.Authorization;
@attribute [Authorize]
<h1>@Model.item.Name</h1>

<link rel="stylesheet" href="~/css/itemdetails.css" />

<div class="product-details">
    <div class="product-pic">
        @if (String.IsNullOrEmpty(@Model.item.PhotoPath))
        {
            <img class="product-image" src="~/ItemImages/no_photo.webp">
        }
        else
        {
            <img class="product-image" src="@Model.item.PhotoPath">
            Console.WriteLine(@Model.item.PhotoPath);
        }
    </div>
    <div class="product-info">
        @if (Model.item.InStock)
        {
            <div style="color: green">
                В наличии
            </div>
            <button class="btn btn-success">В корзину</button>

        }
        else
        {
            <div style="color: darkred">
                Нет в наличии
            </div>
            <button class="btn btn-danger">Уведомить о поступлении</button>

        }
        <div class="product-price">@Model.item.Price ₽</div>
        <div class="product-description">@Model.item.Description</div>
    </div>
</div>

WebCourseProject_Vasilyev/Pages/SellerPage.cshtml
@page
@model WebCourseProject_Vasilyev.Pages.SellerPageModel
@using Microsoft.AspNetCore.Authorization;
@attribute [Authorize]
<link rel="stylesheet" href="~/css/Items.css" / />

<h1>Все товары @Model.seller.Name</h1>
<h3>Рейтинг продавца @Model.seller.Rating</h3>
@if(!String.IsNullOrEmpty(Model.seller.Description)){
    <h5>Описание продавца: @Model.seller.Description</h5>
}
<div class="text-center">
    @foreach (var item in await Model.GetItemsAsync())
    {
        <div class="product">
            <a asp-page="/ItemPage" asp-route-id="@item.Id">
                <div class="product-image">
                    @if(String.IsNullOrEmpty(item.PhotoPath)){
                        <img src="~/ItemImages/no_photo.webp">

                    }
                    else
                    {
                        <img src="@item.PhotoPath">
                    }
                </div>
            </a>
            <div class="product-name">@item.Name</div>
            @if (item.InStock)
            {
                <div style="color: green">
                    В наличии
                </div>
                <div class="product-price">@item.Price ₽</div>
                <button class="btn btn-success">В корзину</button>
            }
            else
            {
                    <div style="color: darkred">
                        Нет в наличии
                    </div>
                    <div class="product-price">@item.Price ₽</div>
                    <button class="btn btn-danger">Уведомить о поступлении</button>

            }
        </div>

    }
</div>

WebCourseProject_Vasilyev/Pages/ShoppingCart.cshtml
@page
@using Microsoft.AspNetCore.Authorization;
@attribute [Authorize]
@model WebCourseProject_Vasilyev.Pages.ShoppingCartModel
@{
}
<div class="container">
  <div class="row">
        @if (TempData.ContainsKey("SuccessMessage"))
        {
            <div class="alert alert-success" role="alert">
                @TempData["SuccessMessage"]
            </div>
        }
    <div class="col-md-8">
      <h2>Корзина покупок</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Название</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Итого</th>
          </tr>
        </thead>
        <tbody>
                    @if (Model.shoppingCart != null)
                    {
                        @foreach (var shoppingCartComponent in Model.shoppingCart.CartItems)
                        {
                            <tr>
                                <td>@shoppingCartComponent.item.Name</td>
                                <td>@shoppingCartComponent.item.Price ₽</td>
                                <td>
                                    <input type="number" value="@shoppingCartComponent.Quantity"/>
                                </td>
                                <td>@(
                                            shoppingCartComponent.item.Price * shoppingCartComponent.Quantity
                                            ) ₽</td>
                            </tr>
                        }

                    }
                </tbody>
      </table>
    </div>
    <form class="col-md-4" method="post">
        <h2>@Model.TotalCostsText</h2>
        <button class="btn btn-primary" asp-action="BuyButtonClick">Оформить заказ</button>
    </form>
  </div>
</div>